name: aoc2023
description: Advent of Code 2023
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.2.2

# Add regular dependencies here.
dependencies:
  dart_numerics: ^0.0.6

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.9
